(ns test-runner
  (:require [cljs.test :refer-macros [run-tests]]
            [hyperopen.config-test]
            [hyperopen.api-test]
            [hyperopen.api.projections-test]
            [hyperopen.api.gateway.orders.commands-test]
            [hyperopen.account.history.actions-test]
            [hyperopen.account.history.effects-test]
            [hyperopen.domain.trading.indicators.math-adapter-test]
            [hyperopen.domain.trading.indicators.contracts-test]
            [hyperopen.domain.trading.indicators.family-parity-test]
            [hyperopen.domain.trading.indicators.flow-branch-coverage-test]
            [hyperopen.domain.trading.indicators.flow-family-coverage-test]
            [hyperopen.domain.trading.indicators.registry-test]
            [hyperopen.domain.trading.indicators.heavy-algorithms-test]
            [hyperopen.domain.trading.indicators.oscillators-family-coverage-test]
            [hyperopen.domain.trading.indicators.structure-test]
            [hyperopen.domain.trading.indicators.trend-family-coverage-test]
            [hyperopen.domain.trading.indicators.volatility-family-coverage-test]
            [hyperopen.domain.funding-history-test]
            [hyperopen.domain.market.instrument-test]
            [hyperopen.domain.trading.order-values-test]
            [hyperopen.platform-test]
            [hyperopen.telemetry-test]
            [hyperopen.telemetry.console-warning-test]
            [hyperopen.websocket.acl.hyperliquid-test]
            [hyperopen.websocket.application.runtime-test]
            [hyperopen.websocket.application.runtime-reducer-test]
            [hyperopen.websocket.diagnostics-actions-test]
            [hyperopen.websocket.diagnostics-effects-test]
            [hyperopen.websocket.diagnostics-copy-test]
            [hyperopen.websocket.diagnostics-payload-test]
            [hyperopen.websocket.diagnostics-runtime-test]
            [hyperopen.websocket.domain.policy-test]
            [hyperopen.websocket.health-projection-test]
            [hyperopen.websocket.health-runtime-test]
            [hyperopen.websocket.infrastructure.runtime-effects-test]
            [hyperopen.websocket.infrastructure.transport-test]
            [hyperopen.asset-selector.actions-test]
            [hyperopen.asset-selector.active-market-cache-test]
            [hyperopen.asset-selector.settings-test]
            [hyperopen.asset-selector.markets-test]
            [hyperopen.asset-selector.markets-cache-test]
            [hyperopen.asset-selector.icon-status-runtime-test]
            [hyperopen.websocket.subscriptions-runtime-test]
            [hyperopen.core-public-actions-test]
            [hyperopen.core-bootstrap-test]
            [hyperopen.utils.data-normalization-test]
            [hyperopen.utils.formatting-test]
            [hyperopen.utils.hl-signing-test]
            [hyperopen.utils.interval-test]
            [hyperopen.websocket.interval-coverage-test]
            [hyperopen.orderbook.actions-test]
            [hyperopen.orderbook.settings-test]
            [hyperopen.orderbook.price-aggregation-test]
            [hyperopen.order.feedback-runtime-test]
            [hyperopen.app.effects-test]
            [hyperopen.chart.settings-test]
            [hyperopen.runtime.api-effects-test]
            [hyperopen.runtime.effect-adapters-test]
            [hyperopen.wallet.actions-test]
            [hyperopen.wallet.address-watcher-test]
            [hyperopen.wallet.connection-runtime-test]
            [hyperopen.wallet.copy-feedback-runtime-test]
            [hyperopen.wallet.agent-runtime-test]
            [hyperopen.websocket.client-test]
            [hyperopen.websocket.orderbook-policy-test]
            [hyperopen.websocket.orderbook-test]
            [hyperopen.websocket.active-asset-ctx-test]
            [hyperopen.websocket.webdata2-test]
            [hyperopen.websocket.market-projection-runtime-test]
            [hyperopen.websocket.trades-policy-test]
            [hyperopen.websocket.trades-test]
            [hyperopen.views.active-asset-view-test]
            [hyperopen.views.app-shell-spacing-test]
            [hyperopen.views.asset-selector-view-test]
            [hyperopen.views.footer-view-test]
            [hyperopen.views.header-view-test]
            [hyperopen.views.trading-chart.chart-type-dropdown-test]
            [hyperopen.views.trading-chart.core-test]
            [hyperopen.views.trading-chart.timeframe-dropdown-test]
            [hyperopen.views.trading-chart.utils.chart-interop-test]
            [hyperopen.views.trading-chart.utils.chart-options-test]
            [hyperopen.views.trading-chart.utils.data-processing-test]
            [hyperopen.views.trading-chart.utils.indicators-test]
            [hyperopen.views.l2-orderbook-view-test]
            [hyperopen.views.typography-scale-test]
            [hyperopen.views.trade.order-form-commands-test]
            [hyperopen.views.trade.order-form-component-primitives-test]
            [hyperopen.views.trade.order-form-component-sections-test]
            [hyperopen.views.trade.order-form-runtime-gateway-test]
            [hyperopen.views.trade.order-form-vm-submit-test]
            [hyperopen.views.trade.order-form-vm-test]
            [hyperopen.views.trade.order-form-view-test]
            [hyperopen.trading.order-form-transitions-test]
            [hyperopen.startup.init-test]
            [hyperopen.startup.collaborators-test]
            [hyperopen.startup.composition-test]
            [hyperopen.startup.runtime-test]
            [hyperopen.runtime.bootstrap-test]
            [hyperopen.runtime.app-effects-test]
            [hyperopen.runtime.collaborators-test]
            [hyperopen.runtime.registry-composition-test]
            [hyperopen.runtime.state-test]
            [hyperopen.schema.chart-interop-contracts-test]
            [hyperopen.schema.contracts-test]
            [hyperopen.schema.contracts-coverage-test]
            [hyperopen.runtime.validation-test]
            [hyperopen.state.app-defaults-test]
            [hyperopen.state.trading-test]
            [hyperopen.ui.preferences-test]))

(defn run-all-tests
  "Run all test namespaces and return the results"
  []
  (run-tests 'hyperopen.api-test
             'hyperopen.api.projections-test
             'hyperopen.api.gateway.orders.commands-test
             'hyperopen.account.history.actions-test
             'hyperopen.account.history.effects-test
             'hyperopen.domain.trading.indicators.math-adapter-test
             'hyperopen.domain.trading.indicators.contracts-test
             'hyperopen.domain.trading.indicators.family-parity-test
             'hyperopen.domain.trading.indicators.flow-branch-coverage-test
             'hyperopen.domain.trading.indicators.flow-family-coverage-test
             'hyperopen.domain.trading.indicators.registry-test
             'hyperopen.domain.trading.indicators.heavy-algorithms-test
             'hyperopen.domain.trading.indicators.oscillators-family-coverage-test
             'hyperopen.domain.trading.indicators.structure-test
             'hyperopen.domain.trading.indicators.trend-family-coverage-test
             'hyperopen.domain.trading.indicators.volatility-family-coverage-test
             'hyperopen.domain.funding-history-test
             'hyperopen.domain.market.instrument-test
             'hyperopen.domain.trading.order-values-test
             'hyperopen.platform-test
             'hyperopen.telemetry-test
             'hyperopen.telemetry.console-warning-test
             'hyperopen.config-test
             'hyperopen.websocket.acl.hyperliquid-test
             'hyperopen.websocket.application.runtime-test
             'hyperopen.websocket.application.runtime-reducer-test
             'hyperopen.websocket.diagnostics-actions-test
             'hyperopen.websocket.diagnostics-effects-test
             'hyperopen.websocket.diagnostics-copy-test
             'hyperopen.websocket.diagnostics-payload-test
             'hyperopen.websocket.diagnostics-runtime-test
             'hyperopen.websocket.domain.policy-test
             'hyperopen.websocket.health-projection-test
             'hyperopen.websocket.health-runtime-test
             'hyperopen.websocket.infrastructure.runtime-effects-test
             'hyperopen.websocket.infrastructure.transport-test
             'hyperopen.websocket.subscriptions-runtime-test
             'hyperopen.utils.data-normalization-test
             'hyperopen.utils.formatting-test
             'hyperopen.utils.hl-signing-test
             'hyperopen.utils.interval-test
             'hyperopen.websocket.interval-coverage-test
             'hyperopen.asset-selector.actions-test
             'hyperopen.asset-selector.active-market-cache-test
             'hyperopen.asset-selector.settings-test
             'hyperopen.asset-selector.markets-test
             'hyperopen.asset-selector.markets-cache-test
             'hyperopen.asset-selector.icon-status-runtime-test
             'hyperopen.core-public-actions-test
             'hyperopen.core-bootstrap-test
             'hyperopen.orderbook.actions-test
             'hyperopen.orderbook.settings-test
             'hyperopen.orderbook.price-aggregation-test
             'hyperopen.order.feedback-runtime-test
             'hyperopen.app.effects-test
             'hyperopen.chart.settings-test
             'hyperopen.runtime.api-effects-test
             'hyperopen.runtime.effect-adapters-test
             'hyperopen.wallet.actions-test
             'hyperopen.wallet.address-watcher-test
             'hyperopen.wallet.connection-runtime-test
             'hyperopen.wallet.copy-feedback-runtime-test
             'hyperopen.wallet.agent-runtime-test
             'hyperopen.websocket.client-test
             'hyperopen.websocket.orderbook-policy-test
             'hyperopen.websocket.orderbook-test
             'hyperopen.websocket.active-asset-ctx-test
             'hyperopen.websocket.webdata2-test
             'hyperopen.websocket.market-projection-runtime-test
             'hyperopen.websocket.trades-policy-test
             'hyperopen.websocket.trades-test
             'hyperopen.views.active-asset-view-test
             'hyperopen.views.app-shell-spacing-test
             'hyperopen.views.asset-selector-view-test
             'hyperopen.views.footer-view-test
             'hyperopen.views.header-view-test
             'hyperopen.views.trading-chart.chart-type-dropdown-test
             'hyperopen.views.trading-chart.core-test
             'hyperopen.views.trading-chart.timeframe-dropdown-test
             'hyperopen.views.trading-chart.utils.chart-interop-test
             'hyperopen.views.trading-chart.utils.chart-options-test
             'hyperopen.views.trading-chart.utils.data-processing-test
             'hyperopen.views.trading-chart.utils.indicators-test
             'hyperopen.views.l2-orderbook-view-test
             'hyperopen.views.typography-scale-test
             'hyperopen.views.trade.order-form-commands-test
             'hyperopen.views.trade.order-form-component-primitives-test
             'hyperopen.views.trade.order-form-component-sections-test
             'hyperopen.views.trade.order-form-runtime-gateway-test
             'hyperopen.views.trade.order-form-vm-submit-test
             'hyperopen.views.trade.order-form-vm-test
             'hyperopen.views.trade.order-form-view-test
             'hyperopen.trading.order-form-transitions-test
             'hyperopen.startup.init-test
             'hyperopen.startup.collaborators-test
             'hyperopen.startup.composition-test
             'hyperopen.startup.runtime-test
             'hyperopen.runtime.bootstrap-test
             'hyperopen.runtime.app-effects-test
             'hyperopen.runtime.collaborators-test
             'hyperopen.runtime.registry-composition-test
             'hyperopen.runtime.state-test
             'hyperopen.schema.chart-interop-contracts-test
             'hyperopen.schema.contracts-test
             'hyperopen.schema.contracts-coverage-test
             'hyperopen.runtime.validation-test
             'hyperopen.state.app-defaults-test
             'hyperopen.state.trading-test
             'hyperopen.ui.preferences-test))

(defn -main
  "Entry point for test runner"
  []
  (println "\n=== Running Hyperopen Tests ===")
  (let [results (run-all-tests)]
    (println "\n=== Test Results ===")
    results))

;; Run tests when this namespace loads in test environment
(-main)
