(ns hyperopen.schema.runtime-registration.portfolio)

(def effect-binding-rows
  [[:effects/run-portfolio-optimizer :run-portfolio-optimizer]])

(def action-binding-rows
  [[:actions/toggle-portfolio-summary-scope-dropdown :toggle-portfolio-summary-scope-dropdown]
   [:actions/select-portfolio-summary-scope :select-portfolio-summary-scope]
   [:actions/toggle-portfolio-summary-time-range-dropdown :toggle-portfolio-summary-time-range-dropdown]
   [:actions/toggle-portfolio-performance-metrics-time-range-dropdown :toggle-portfolio-performance-metrics-time-range-dropdown]
   [:actions/open-portfolio-fee-schedule :open-portfolio-fee-schedule]
   [:actions/close-portfolio-fee-schedule :close-portfolio-fee-schedule]
   [:actions/toggle-portfolio-fee-schedule-referral-dropdown :toggle-portfolio-fee-schedule-referral-dropdown]
   [:actions/toggle-portfolio-fee-schedule-staking-dropdown :toggle-portfolio-fee-schedule-staking-dropdown]
   [:actions/toggle-portfolio-fee-schedule-maker-rebate-dropdown :toggle-portfolio-fee-schedule-maker-rebate-dropdown]
   [:actions/toggle-portfolio-fee-schedule-market-dropdown :toggle-portfolio-fee-schedule-market-dropdown]
   [:actions/select-portfolio-fee-schedule-referral-discount :select-portfolio-fee-schedule-referral-discount]
   [:actions/select-portfolio-fee-schedule-staking-tier :select-portfolio-fee-schedule-staking-tier]
   [:actions/select-portfolio-fee-schedule-maker-rebate-tier :select-portfolio-fee-schedule-maker-rebate-tier]
   [:actions/select-portfolio-fee-schedule-market-type :select-portfolio-fee-schedule-market-type]
   [:actions/handle-portfolio-fee-schedule-keydown :handle-portfolio-fee-schedule-keydown]
   [:actions/select-portfolio-summary-time-range :select-portfolio-summary-time-range]
   [:actions/select-portfolio-chart-tab :select-portfolio-chart-tab]
   [:actions/set-portfolio-account-info-tab :set-portfolio-account-info-tab]
   [:actions/set-portfolio-returns-benchmark-search :set-portfolio-returns-benchmark-search]
   [:actions/set-portfolio-returns-benchmark-suggestions-open :set-portfolio-returns-benchmark-suggestions-open]
   [:actions/select-portfolio-returns-benchmark :select-portfolio-returns-benchmark]
   [:actions/remove-portfolio-returns-benchmark :remove-portfolio-returns-benchmark]
   [:actions/handle-portfolio-returns-benchmark-search-keydown :handle-portfolio-returns-benchmark-search-keydown]
   [:actions/clear-portfolio-returns-benchmark :clear-portfolio-returns-benchmark]
   [:actions/open-portfolio-volume-history :open-portfolio-volume-history]
   [:actions/close-portfolio-volume-history :close-portfolio-volume-history]
   [:actions/handle-portfolio-volume-history-keydown :handle-portfolio-volume-history-keydown]
   [:actions/run-portfolio-optimizer :run-portfolio-optimizer]])
