(ns hyperopen.portfolio.optimizer.contracts
  (:require [hyperopen.portfolio.optimizer.contracts.constants :as constants]
            [hyperopen.portfolio.optimizer.contracts.migrations :as migrations]
            [hyperopen.portfolio.optimizer.contracts.paths :as paths]
            [hyperopen.portfolio.optimizer.contracts.signatures :as signatures]
            [hyperopen.portfolio.optimizer.contracts.worker-wire :as worker-wire]))

(def draft-schema-version migrations/draft-schema-version)
(def scenario-record-schema-version migrations/scenario-record-schema-version)
(def tracking-record-schema-version migrations/tracking-record-schema-version)
(def request-signature-schema-version signatures/request-signature-schema-version)
(def result-payload-schema-version constants/result-payload-schema-version)
(def worker-wire-schema-version worker-wire/worker-wire-schema-version)

(def optimizer-path paths/optimizer-path)
(def draft-path paths/draft-path)
(def draft-id-path paths/draft-id-path)
(def draft-name-path paths/draft-name-path)
(def draft-status-path paths/draft-status-path)
(def draft-universe-path paths/draft-universe-path)
(def draft-objective-path paths/draft-objective-path)
(def draft-return-model-path paths/draft-return-model-path)
(def draft-return-model-views-path paths/draft-return-model-views-path)
(def draft-risk-model-path paths/draft-risk-model-path)
(def draft-constraints-path paths/draft-constraints-path)
(def draft-execution-assumptions-path paths/draft-execution-assumptions-path)
(def draft-history-assumptions-path paths/draft-history-assumptions-path)
(def draft-proxy-reference-instruments-path
  paths/draft-proxy-reference-instruments-path)
(def draft-metadata-path paths/draft-metadata-path)
(def draft-dirty-path paths/draft-dirty-path)
(def draft-universe-source-path paths/draft-universe-source-path)
(def draft-persist-path paths/draft-persist-path)
(def active-scenario-path paths/active-scenario-path)
(def active-scenario-loaded-id-path paths/active-scenario-loaded-id-path)
(def active-scenario-name-path paths/active-scenario-name-path)
(def active-scenario-status-path paths/active-scenario-status-path)
(def active-scenario-read-only-path paths/active-scenario-read-only-path)
(def run-state-path paths/run-state-path)
(def run-state-status-path paths/run-state-status-path)
(def runtime-path paths/runtime-path)
(def runtime-as-of-ms-path paths/runtime-as-of-ms-path)
(def runtime-stale-after-ms-path paths/runtime-stale-after-ms-path)
(def runtime-funding-periods-per-year-path paths/runtime-funding-periods-per-year-path)
(def runtime-orderbook-stale-after-ms-path paths/runtime-orderbook-stale-after-ms-path)
(def history-data-path paths/history-data-path)
(def history-discovery-path paths/history-discovery-path)
(def market-cap-by-coin-path paths/market-cap-by-coin-path)
(def history-load-state-path paths/history-load-state-path)
(def history-load-state-status-path paths/history-load-state-status-path)
(def history-load-state-request-signature-path
  paths/history-load-state-request-signature-path)
(def history-prefetch-path paths/history-prefetch-path)
(def history-prefetch-active-instrument-id-path
  paths/history-prefetch-active-instrument-id-path)
(def optimization-progress-path paths/optimization-progress-path)
(def optimization-progress-status-path paths/optimization-progress-status-path)
(def scenario-index-path paths/scenario-index-path)
(def scenario-save-state-path paths/scenario-save-state-path)
(def scenario-load-state-path paths/scenario-load-state-path)
(def scenario-index-load-state-path paths/scenario-index-load-state-path)
(def scenario-archive-state-path paths/scenario-archive-state-path)
(def scenario-duplicate-state-path paths/scenario-duplicate-state-path)
(def scenario-save-modal-path paths/scenario-save-modal-path)
(def scenario-save-modal-error-path paths/scenario-save-modal-error-path)
(def last-successful-run-path paths/last-successful-run-path)
(def last-successful-run-result-path paths/last-successful-run-result-path)
(def constraint-profiles-path paths/constraint-profiles-path)
(def view-library-path paths/view-library-path)
(def assumption-library-path paths/assumption-library-path)
(def refinement-path paths/refinement-path)
(def refinement-active-path paths/refinement-active-path)
(def refinement-depth-path paths/refinement-depth-path)
(def refinement-requested-points-path paths/refinement-requested-points-path)
(def refinement-baseline-result-path paths/refinement-baseline-result-path)
(def execution-modal-path paths/execution-modal-path)
(def execution-modal-error-path paths/execution-modal-error-path)
(def execution-modal-submitting-path paths/execution-modal-submitting-path)
(def execution-path paths/execution-path)
(def execution-history-path paths/execution-history-path)
(def execution-run-attempt-path paths/execution-run-attempt-path)
(def execution-abort-requested-path paths/execution-abort-requested-path)
(def execution-persistence-error-path paths/execution-persistence-error-path)
(def execution-resting-carryover-path paths/execution-resting-carryover-path)
(def tracking-path paths/tracking-path)
(def tracking-error-path paths/tracking-error-path)
(def optimizer-ui-path paths/optimizer-ui-path)
(def ui-list-filter-path paths/ui-list-filter-path)
(def ui-list-sort-path paths/ui-list-sort-path)
(def ui-workspace-panel-path paths/ui-workspace-panel-path)
(def ui-results-tab-path paths/ui-results-tab-path)
(def ui-diagnostics-tab-path paths/ui-diagnostics-tab-path)
(def ui-universe-search-query-path paths/ui-universe-search-query-path)
(def ui-universe-search-active-index-path paths/ui-universe-search-active-index-path)
(def ui-universe-search-type-filter-path paths/ui-universe-search-type-filter-path)
(def ui-universe-search-quote-filter-path paths/ui-universe-search-quote-filter-path)
(def ui-proxy-search-queries-path paths/ui-proxy-search-queries-path)
(def ui-history-assumption-active-path paths/ui-history-assumption-active-path)
(def ui-draft-add-asset-open-path paths/ui-draft-add-asset-open-path)
(def ui-selected-risk-instrument-path paths/ui-selected-risk-instrument-path)
(def ui-objective-menu-open-path paths/ui-objective-menu-open-path)
(def ui-scenario-menu-open-path paths/ui-scenario-menu-open-path)
(def ui-objective-menu-selection-path paths/ui-objective-menu-selection-path)
(def ui-objective-menu-view-order-path paths/ui-objective-menu-view-order-path)
(def ui-objective-menu-view-drafts-path paths/ui-objective-menu-view-drafts-path)
(def ui-objective-menu-target-sigma-path paths/ui-objective-menu-target-sigma-path)
(def ui-black-litterman-editor-path paths/ui-black-litterman-editor-path)
(def ui-frontier-overlay-mode-path paths/ui-frontier-overlay-mode-path)
(def ui-target-sigma-draft-path paths/ui-target-sigma-draft-path)
(def ui-constrain-frontier-path paths/ui-constrain-frontier-path)
(def ui-stale-auto-recompute-path paths/ui-stale-auto-recompute-path)
(def ui-refinement-depth-path paths/ui-refinement-depth-path)
(def ui-exposure-zoom-level-path paths/ui-exposure-zoom-level-path)
(def ui-return-views-filter-path paths/ui-return-views-filter-path)
(def ui-return-views-io-note-path paths/ui-return-views-io-note-path)
(def ui-history-assumptions-io-note-path paths/ui-history-assumptions-io-note-path)
(def path-catalog paths/path-catalog)
(def optimizer-state-path paths/optimizer-state-path)
(def optimizer-ui-state-path paths/optimizer-ui-state-path)
(def contract-path paths/contract-path)

(def draft-statuses constants/draft-statuses)
(def scenario-record-statuses constants/scenario-record-statuses)
(def tracking-snapshot-statuses constants/tracking-snapshot-statuses)
(def result-payload-statuses constants/result-payload-statuses)
(def objective-kinds constants/objective-kinds)
(def return-model-kinds constants/return-model-kinds)
(def risk-model-kinds constants/risk-model-kinds)
(def history-assumption-behaviors constants/history-assumption-behaviors)

(def contract-specs
  {:optimizer/draft ::draft
   :optimizer/engine-request ::engine-request
   :optimizer/request-signature ::request-signature
   :optimizer/scenario-record ::scenario-record
   :optimizer/tracking-record ::tracking-record
   :optimizer/tracking-snapshot ::tracking-snapshot
   :optimizer/result-payload ::result-payload
   :optimizer/worker-envelope ::worker-envelope})

(def migrate-draft migrations/migrate-draft)
(def migrate-scenario-record migrations/migrate-scenario-record)
(def migrate-tracking-record migrations/migrate-tracking-record)
(def migrate-contract migrations/migrate-contract)

(def optimizer-input-keys signatures/optimizer-input-keys)
(def optimizer-input-signature signatures/optimizer-input-signature)
(def build-request-signature signatures/build-request-signature)

(def enum-value-keys worker-wire/enum-value-keys)
(def instrument-keyed-map-keys worker-wire/instrument-keyed-map-keys)
(def instrument-keyed-map-paths worker-wire/instrument-keyed-map-paths)
(def instrument-id-key worker-wire/instrument-id-key)
(def stringify-instrument-keyed-map worker-wire/stringify-instrument-keyed-map)
(def normalize-wire-values worker-wire/normalize-wire-values)
(def normalize-instrument-keyed-maps worker-wire/normalize-instrument-keyed-maps)
(def normalize-worker-boundary worker-wire/normalize-worker-boundary)
