(ns hyperopen.portfolio.optimizer.runtime-catalog
  (:require [hyperopen.portfolio.optimizer.actions :as actions]
            [hyperopen.portfolio.optimizer.black-litterman-actions :as bl-actions]
            [hyperopen.portfolio.optimizer.frontier-actions :as frontier-actions]
            [hyperopen.runtime.effect-adapters.portfolio-optimizer :as effect-adapters]
            [hyperopen.runtime.effect-adapters.portfolio-optimizer-io :as effect-adapters-io]))

(defn action-deps
  []
  {:portfolio-optimizer
   {:run-portfolio-optimizer actions/run-portfolio-optimizer
    :set-portfolio-optimizer-objective-kind
    actions/set-portfolio-optimizer-objective-kind
    :open-portfolio-optimizer-objective-menu
    actions/open-portfolio-optimizer-objective-menu
    :close-portfolio-optimizer-objective-menu
    actions/close-portfolio-optimizer-objective-menu
    :handle-portfolio-optimizer-objective-menu-keydown
    actions/handle-portfolio-optimizer-objective-menu-keydown
    :select-portfolio-optimizer-objective-menu-option
    actions/select-portfolio-optimizer-objective-menu-option
    :set-portfolio-optimizer-objective-menu-view-return
    actions/set-portfolio-optimizer-objective-menu-view-return
    :step-portfolio-optimizer-objective-menu-view-return
    actions/step-portfolio-optimizer-objective-menu-view-return
    :set-portfolio-optimizer-objective-menu-view-confidence
    actions/set-portfolio-optimizer-objective-menu-view-confidence
    :remove-portfolio-optimizer-objective-menu-view
    actions/remove-portfolio-optimizer-objective-menu-view
    :add-portfolio-optimizer-objective-menu-view
    actions/add-portfolio-optimizer-objective-menu-view
    :apply-portfolio-optimizer-objective-menu-selection-and-run
    actions/apply-portfolio-optimizer-objective-menu-selection-and-run
    :switch-portfolio-optimizer-objective-and-run
    actions/switch-portfolio-optimizer-objective-and-run
    :set-portfolio-optimizer-return-views-filter
    actions/set-portfolio-optimizer-return-views-filter
    :export-portfolio-optimizer-return-views
    actions/export-portfolio-optimizer-return-views
    :import-portfolio-optimizer-return-views
    actions/import-portfolio-optimizer-return-views
    :apply-imported-portfolio-optimizer-return-views
    actions/apply-imported-portfolio-optimizer-return-views
    :dismiss-portfolio-optimizer-return-views-io-note
    actions/dismiss-portfolio-optimizer-return-views-io-note
    :export-portfolio-optimizer-history-assumptions
    actions/export-portfolio-optimizer-history-assumptions
    :import-portfolio-optimizer-history-assumptions
    actions/import-portfolio-optimizer-history-assumptions
    :apply-imported-portfolio-optimizer-history-assumptions
    actions/apply-imported-portfolio-optimizer-history-assumptions
    :dismiss-portfolio-optimizer-history-assumptions-io-note
    actions/dismiss-portfolio-optimizer-history-assumptions-io-note
    :apply-portfolio-optimizer-recommended-history-assumption
    actions/apply-portfolio-optimizer-recommended-history-assumption
    :apply-portfolio-optimizer-recommended-history-assumptions
    actions/apply-portfolio-optimizer-recommended-history-assumptions
    :set-portfolio-optimizer-return-model-kind
    actions/set-portfolio-optimizer-return-model-kind
    :set-portfolio-optimizer-risk-model-kind
    actions/set-portfolio-optimizer-risk-model-kind
    :apply-portfolio-optimizer-setup-preset
    actions/apply-portfolio-optimizer-setup-preset
    :set-portfolio-optimizer-constraint
    actions/set-portfolio-optimizer-constraint
    :set-portfolio-optimizer-exposure-point
    actions/set-portfolio-optimizer-exposure-point
    :set-portfolio-optimizer-exposure-band
    actions/set-portfolio-optimizer-exposure-band
    :apply-portfolio-optimizer-exposure-preset
    actions/apply-portfolio-optimizer-exposure-preset
    :set-portfolio-optimizer-exposure-zoom-level
    actions/set-portfolio-optimizer-exposure-zoom-level
    :reset-portfolio-optimizer-constraints-to-system
    actions/reset-portfolio-optimizer-constraints-to-system
    :save-portfolio-optimizer-constraint-default
    actions/save-portfolio-optimizer-constraint-default
    :apply-portfolio-optimizer-constraint-default
    actions/apply-portfolio-optimizer-constraint-default
    :set-portfolio-optimizer-objective-parameter
    actions/set-portfolio-optimizer-objective-parameter
    :set-portfolio-optimizer-objective-parameter-percent
    actions/set-portfolio-optimizer-objective-parameter-percent
    :set-portfolio-optimizer-target-sigma-draft
    actions/set-portfolio-optimizer-target-sigma-draft
    :set-portfolio-optimizer-objective-menu-target-sigma
    actions/set-portfolio-optimizer-objective-menu-target-sigma
    :reset-portfolio-optimizer-target-sigma-draft
    actions/reset-portfolio-optimizer-target-sigma-draft
    :rerun-portfolio-optimizer-at-target-sigma
    actions/rerun-portfolio-optimizer-at-target-sigma
    :set-portfolio-optimizer-execution-assumption
    actions/set-portfolio-optimizer-execution-assumption
    :add-portfolio-optimizer-black-litterman-view
    bl-actions/add-portfolio-optimizer-black-litterman-view
    :set-portfolio-optimizer-black-litterman-view-parameter
    bl-actions/set-portfolio-optimizer-black-litterman-view-parameter
    :remove-portfolio-optimizer-black-litterman-view
    bl-actions/remove-portfolio-optimizer-black-litterman-view
    :set-portfolio-optimizer-black-litterman-editor-type
    bl-actions/set-portfolio-optimizer-black-litterman-editor-type
    :set-portfolio-optimizer-black-litterman-editor-field
    bl-actions/set-portfolio-optimizer-black-litterman-editor-field
    :save-portfolio-optimizer-black-litterman-editor-view
    bl-actions/save-portfolio-optimizer-black-litterman-editor-view
    :edit-portfolio-optimizer-black-litterman-view
    bl-actions/edit-portfolio-optimizer-black-litterman-view
    :cancel-portfolio-optimizer-black-litterman-edit
    bl-actions/cancel-portfolio-optimizer-black-litterman-edit
    :request-clear-portfolio-optimizer-black-litterman-views
    bl-actions/request-clear-portfolio-optimizer-black-litterman-views
    :cancel-clear-portfolio-optimizer-black-litterman-views
    bl-actions/cancel-clear-portfolio-optimizer-black-litterman-views
    :confirm-clear-portfolio-optimizer-black-litterman-views
    bl-actions/confirm-clear-portfolio-optimizer-black-litterman-views
    :set-portfolio-optimizer-instrument-filter
    actions/set-portfolio-optimizer-instrument-filter
    :set-portfolio-optimizer-asset-override
    actions/set-portfolio-optimizer-asset-override
    :set-portfolio-optimizer-history-assumption-mode
    actions/set-portfolio-optimizer-history-assumption-mode
    :set-portfolio-optimizer-history-assumption-expected-return
    actions/set-portfolio-optimizer-history-assumption-expected-return
    :set-portfolio-optimizer-history-assumption-expected-volatility
    actions/set-portfolio-optimizer-history-assumption-expected-volatility
    :set-portfolio-optimizer-history-assumption-max-weight-cap
    actions/set-portfolio-optimizer-history-assumption-max-weight-cap
    :clear-portfolio-optimizer-history-assumption
    actions/clear-portfolio-optimizer-history-assumption
    :set-portfolio-optimizer-history-assumption-proxy-asset
    actions/set-portfolio-optimizer-history-assumption-proxy-asset
    :set-portfolio-optimizer-history-assumption-proxy-search
    actions/set-portfolio-optimizer-history-assumption-proxy-search
    :set-portfolio-optimizer-history-assumption-relationship-strength
    actions/set-portfolio-optimizer-history-assumption-relationship-strength
    :apply-portfolio-optimizer-history-assumption
    actions/apply-portfolio-optimizer-history-assumption
    :reset-portfolio-optimizer-history-assumption
    actions/reset-portfolio-optimizer-history-assumption
    :set-portfolio-optimizer-history-assumption-active
    actions/set-portfolio-optimizer-history-assumption-active
    :hydrate-portfolio-optimizer-history-assumption-library
    actions/hydrate-portfolio-optimizer-history-assumption-library
    :hydrate-portfolio-optimizer-view-library
    actions/hydrate-portfolio-optimizer-view-library
    :set-portfolio-optimizer-universe-search-query
    actions/set-portfolio-optimizer-universe-search-query
    :set-portfolio-optimizer-draft-add-asset-open
    actions/set-portfolio-optimizer-draft-add-asset-open
    :handle-portfolio-optimizer-universe-search-keydown
    actions/handle-portfolio-optimizer-universe-search-keydown
    :handle-portfolio-optimizer-draft-add-asset-keydown
    actions/handle-portfolio-optimizer-draft-add-asset-keydown
    :set-portfolio-optimizer-frontier-overlay-mode
    frontier-actions/set-portfolio-optimizer-frontier-overlay-mode
    :set-portfolio-optimizer-constrain-frontier
    frontier-actions/set-portfolio-optimizer-constrain-frontier
    :set-portfolio-optimizer-results-tab
    actions/set-portfolio-optimizer-results-tab
    :set-portfolio-optimizer-selected-risk-instrument
    actions/set-portfolio-optimizer-selected-risk-instrument
    :add-portfolio-optimizer-universe-instrument
    actions/add-portfolio-optimizer-universe-instrument
    :add-portfolio-optimizer-universe-instrument-and-run
    actions/add-portfolio-optimizer-universe-instrument-and-run
    :toggle-portfolio-optimizer-universe-instrument-exclusion-and-run
    actions/toggle-portfolio-optimizer-universe-instrument-exclusion-and-run
    :set-portfolio-optimizer-universe-instrument-side
    actions/set-portfolio-optimizer-universe-instrument-side
    :set-portfolio-optimizer-universe-instrument-side-and-run
    actions/set-portfolio-optimizer-universe-instrument-side-and-run
    :remove-portfolio-optimizer-universe-instrument
    actions/remove-portfolio-optimizer-universe-instrument
    :set-portfolio-optimizer-universe-from-current
    actions/set-portfolio-optimizer-universe-from-current
    :clear-portfolio-optimizer-universe
    actions/clear-portfolio-optimizer-universe
    :restore-or-preseed-portfolio-optimizer-draft
    actions/restore-or-preseed-portfolio-optimizer-draft
    :hydrate-portfolio-optimizer-draft
    actions/hydrate-portfolio-optimizer-draft
    :load-portfolio-optimizer-history-from-draft
    actions/load-portfolio-optimizer-history-from-draft
    :save-portfolio-optimizer-scenario-from-current
    actions/save-portfolio-optimizer-scenario-from-current
    :open-portfolio-optimizer-scenario-save-modal
    actions/open-portfolio-optimizer-scenario-save-modal
    :close-portfolio-optimizer-scenario-save-modal
    actions/close-portfolio-optimizer-scenario-save-modal
    :set-portfolio-optimizer-scenario-save-name
    actions/set-portfolio-optimizer-scenario-save-name
    :confirm-portfolio-optimizer-scenario-save
    actions/confirm-portfolio-optimizer-scenario-save
    :toggle-portfolio-optimizer-scenario-menu
    actions/toggle-portfolio-optimizer-scenario-menu
    :close-portfolio-optimizer-scenario-menu
    actions/close-portfolio-optimizer-scenario-menu
    :handle-portfolio-optimizer-scenario-menu-keydown
    actions/handle-portfolio-optimizer-scenario-menu-keydown
    :new-portfolio-optimizer-scenario
    actions/new-portfolio-optimizer-scenario
    :load-portfolio-optimizer-route
    actions/load-portfolio-optimizer-route
    :archive-portfolio-optimizer-scenario
    actions/archive-portfolio-optimizer-scenario
    :duplicate-portfolio-optimizer-scenario
    actions/duplicate-portfolio-optimizer-scenario
    :open-portfolio-optimizer-execution
    actions/open-portfolio-optimizer-execution
    :set-portfolio-optimizer-execution-phase
    actions/set-portfolio-optimizer-execution-phase
    :set-portfolio-optimizer-execution-default-order-type
    actions/set-portfolio-optimizer-execution-default-order-type
    :set-portfolio-optimizer-execution-row-order-type
    actions/set-portfolio-optimizer-execution-row-order-type
    :toggle-portfolio-optimizer-execution-row
    actions/toggle-portfolio-optimizer-execution-row
    :set-portfolio-optimizer-execution-row-param
    actions/set-portfolio-optimizer-execution-row-param
    :confirm-portfolio-optimizer-execution
    actions/confirm-portfolio-optimizer-execution
    :amend-portfolio-optimizer-execution-order
    actions/amend-portfolio-optimizer-execution-order
    :resume-portfolio-optimizer-execution
    actions/resume-portfolio-optimizer-execution
    :revert-portfolio-optimizer-execution-filled
    actions/revert-portfolio-optimizer-execution-filled
    :restage-portfolio-optimizer-execution-smaller
    actions/restage-portfolio-optimizer-execution-smaller
    :pause-portfolio-optimizer-execution
    actions/pause-portfolio-optimizer-execution
    :discard-portfolio-optimizer-execution
    actions/discard-portfolio-optimizer-execution
    :open-portfolio-optimizer-execution-in-ticket
    actions/open-portfolio-optimizer-execution-in-ticket
    :set-portfolio-optimizer-execution-order-filter
    actions/set-portfolio-optimizer-execution-order-filter
    :set-portfolio-optimizer-execution-overlap-cancel
    actions/set-portfolio-optimizer-execution-overlap-cancel
    :set-portfolio-optimizer-execution-exit
    actions/set-portfolio-optimizer-execution-exit
    :restage-portfolio-optimizer-execution-plan
    actions/restage-portfolio-optimizer-execution-plan
    :set-portfolio-optimizer-execution-auto-exit
    actions/set-portfolio-optimizer-execution-auto-exit
    :refresh-portfolio-optimizer-tracking
    actions/refresh-portfolio-optimizer-tracking
    :enable-portfolio-optimizer-manual-tracking
    actions/enable-portfolio-optimizer-manual-tracking
    :auto-recompute-stale-portfolio-optimizer-scenario
    actions/auto-recompute-stale-portfolio-optimizer-scenario
    :run-portfolio-optimizer-from-draft
    actions/run-portfolio-optimizer-from-draft
    :set-portfolio-optimizer-refinement-depth
    actions/set-portfolio-optimizer-refinement-depth
    :refine-portfolio-optimizer
    actions/refine-portfolio-optimizer
    :stop-portfolio-optimizer-refinement
    actions/stop-portfolio-optimizer-refinement}})

(defn effect-deps
  [runtime]
  (let [optimizer-controller-resolver
        (effect-adapters/make-portfolio-optimizer-controller-resolver runtime)]
    {:portfolio-optimizer
     {:run-portfolio-optimizer
      (effect-adapters/make-run-portfolio-optimizer
       runtime
       optimizer-controller-resolver)
      :run-portfolio-optimizer-pipeline
      (effect-adapters/make-run-portfolio-optimizer-pipeline
       runtime
       optimizer-controller-resolver)
      :load-portfolio-optimizer-history
      effect-adapters/load-portfolio-optimizer-history-effect
      :load-portfolio-optimizer-history-discovery
      effect-adapters/load-portfolio-optimizer-history-discovery-effect
      :load-portfolio-optimizer-scenario-index
      effect-adapters/load-portfolio-optimizer-scenario-index-effect
      :load-portfolio-optimizer-scenario
      effect-adapters/load-portfolio-optimizer-scenario-effect
      :archive-portfolio-optimizer-scenario
      effect-adapters/archive-portfolio-optimizer-scenario-effect
      :duplicate-portfolio-optimizer-scenario
      effect-adapters/duplicate-portfolio-optimizer-scenario-effect
      :save-portfolio-optimizer-scenario
      effect-adapters/save-portfolio-optimizer-scenario-effect
      :execute-portfolio-optimizer-plan
      effect-adapters/execute-portfolio-optimizer-plan-effect
      :refresh-portfolio-optimizer-open-orders
      effect-adapters/refresh-portfolio-optimizer-open-orders-effect
      :refresh-portfolio-optimizer-tracking
      effect-adapters/refresh-portfolio-optimizer-tracking-effect
      :refresh-portfolio-optimizer-rebalance-slippage-snapshots
      effect-adapters/refresh-portfolio-optimizer-rebalance-slippage-snapshots-effect
      :enable-portfolio-optimizer-manual-tracking
      effect-adapters/enable-portfolio-optimizer-manual-tracking-effect
      :save-portfolio-optimizer-constraint-default
      effect-adapters/save-portfolio-optimizer-constraint-default-effect
      :load-portfolio-optimizer-constraint-profiles
      effect-adapters/load-portfolio-optimizer-constraint-profiles-effect
      :load-portfolio-optimizer-view-library
      effect-adapters/load-portfolio-optimizer-view-library-effect
      :sync-portfolio-optimizer-view-library
      effect-adapters/sync-portfolio-optimizer-view-library-effect
      :download-portfolio-optimizer-return-views-file
      effect-adapters/download-portfolio-optimizer-return-views-file-effect
      :pick-portfolio-optimizer-return-views-file
      effect-adapters/pick-portfolio-optimizer-return-views-file-effect
      :download-portfolio-optimizer-history-assumptions-file
      effect-adapters-io/download-portfolio-optimizer-history-assumptions-file-effect
      :pick-portfolio-optimizer-history-assumptions-file
      effect-adapters-io/pick-portfolio-optimizer-history-assumptions-file-effect
      :load-portfolio-optimizer-assumption-library
      effect-adapters/load-portfolio-optimizer-assumption-library-effect
      :sync-portfolio-optimizer-assumption-library
      effect-adapters/sync-portfolio-optimizer-assumption-library-effect
      :restore-portfolio-optimizer-draft
      effect-adapters/restore-portfolio-optimizer-draft-effect
      :reset-portfolio-optimizer-draft
      effect-adapters/reset-portfolio-optimizer-draft-effect}}))
