(ns hyperopen.views.portfolio.vm.history
  (:require [hyperopen.portfolio.application.history :as history]))

(def summary-window-cutoff-ms history/summary-window-cutoff-ms)
(def history-point-value history/history-point-value)
(def history-point-time-ms history/history-point-time-ms)
(def account-value-history-rows history/account-value-history-rows)
(def pnl-history-rows history/pnl-history-rows)
(def normalized-history-rows history/normalized-history-rows)
(def history-window-rows history/history-window-rows)
(def rebase-history-rows history/rebase-history-rows)
(def benchmark-time-range history/benchmark-time-range)
(def market-benchmark-anchor-time-ms history/market-benchmark-anchor-time-ms)
(def range-all-time-key history/range-all-time-key)
(def pnl-delta history/pnl-delta)
(def candle-point-close history/candle-point-close)
(def benchmark-candle-points history/benchmark-candle-points)
(def benchmark-market-return-rows history/benchmark-market-return-rows)
(def aligned-benchmark-return-rows history/aligned-benchmark-return-rows)
(def cumulative-return-time-points history/cumulative-return-time-points)
(def aligned-summary-return-rows history/aligned-summary-return-rows)
(def cumulative-return-row-pairs history/cumulative-return-row-pairs)
