(ns hyperopen.schema.runtime-registration-catalog
  (:require [hyperopen.schema.order-form-command-catalog :as order-form-command-catalog]))

(def ^:private effect-binding-rows-data
  [[:effects/save :save]
   [:effects/save-many :save-many]
   [:effects/local-storage-set :local-storage-set]
   [:effects/local-storage-set-json :local-storage-set-json]
   [:effects/queue-asset-icon-status :queue-asset-icon-status]
   [:effects/sync-asset-selector-active-ctx-subscriptions :sync-asset-selector-active-ctx-subscriptions]
   [:effects/push-state :push-state]
   [:effects/replace-state :replace-state]
   [:effects/init-websocket :init-websocket]
   [:effects/subscribe-active-asset :subscribe-active-asset]
   [:effects/sync-active-candle-subscription :sync-active-candle-subscription]
   [:effects/subscribe-orderbook :subscribe-orderbook]
   [:effects/subscribe-trades :subscribe-trades]
   [:effects/subscribe-webdata2 :subscribe-webdata2]
   [:effects/fetch-candle-snapshot :fetch-candle-snapshot]
   [:effects/unsubscribe-active-asset :unsubscribe-active-asset]
   [:effects/unsubscribe-orderbook :unsubscribe-orderbook]
   [:effects/unsubscribe-trades :unsubscribe-trades]
   [:effects/unsubscribe-webdata2 :unsubscribe-webdata2]
   [:effects/connect-wallet :connect-wallet]
   [:effects/disconnect-wallet :disconnect-wallet]
   [:effects/enable-agent-trading :enable-agent-trading]
   [:effects/set-agent-storage-mode :set-agent-storage-mode]
   [:effects/copy-wallet-address :copy-wallet-address]
   [:effects/reconnect-websocket :reconnect-websocket]
   [:effects/refresh-websocket-health :refresh-websocket-health]
   [:effects/confirm-ws-diagnostics-reveal :confirm-ws-diagnostics-reveal]
   [:effects/copy-websocket-diagnostics :copy-websocket-diagnostics]
   [:effects/ws-reset-subscriptions :ws-reset-subscriptions]
   [:effects/fetch-asset-selector-markets :fetch-asset-selector-markets]
   [:effects/sync-active-asset-funding-predictability :sync-active-asset-funding-predictability]
   [:effects/api-fetch-user-funding-history :api-fetch-user-funding-history]
   [:effects/api-fetch-historical-orders :api-fetch-historical-orders]
   [:effects/export-funding-history-csv :export-funding-history-csv]
   [:effects/api-fetch-predicted-fundings :api-fetch-predicted-fundings]
   [:effects/api-submit-order :api-submit-order]
   [:effects/api-cancel-order :api-cancel-order]
   [:effects/api-submit-position-tpsl :api-submit-position-tpsl]
   [:effects/api-submit-position-margin :api-submit-position-margin]
   [:effects/api-load-user-data :api-load-user-data]
   [:effects/api-fetch-vault-index :api-fetch-vault-index]
   [:effects/api-fetch-vault-summaries :api-fetch-vault-summaries]
   [:effects/api-fetch-user-vault-equities :api-fetch-user-vault-equities]
   [:effects/api-fetch-vault-details :api-fetch-vault-details]
   [:effects/api-fetch-vault-webdata2 :api-fetch-vault-webdata2]
   [:effects/api-fetch-vault-fills :api-fetch-vault-fills]
   [:effects/api-fetch-vault-funding-history :api-fetch-vault-funding-history]
   [:effects/api-fetch-vault-order-history :api-fetch-vault-order-history]
   [:effects/api-fetch-vault-ledger-updates :api-fetch-vault-ledger-updates]
   [:effects/api-submit-vault-transfer :api-submit-vault-transfer]
   [:effects/api-fetch-hyperunit-fee-estimate :api-fetch-hyperunit-fee-estimate]
   [:effects/api-fetch-hyperunit-withdrawal-queue :api-fetch-hyperunit-withdrawal-queue]
   [:effects/api-submit-funding-transfer :api-submit-funding-transfer]
   [:effects/api-submit-funding-withdraw :api-submit-funding-withdraw]
   [:effects/api-submit-funding-deposit :api-submit-funding-deposit]])

(def ^:private action-binding-rows-data
  (vec
   (concat
    [[:actions/init-websockets :init-websockets]
     [:actions/subscribe-to-asset :subscribe-to-asset]
     [:actions/subscribe-to-webdata2 :subscribe-to-webdata2]
     [:actions/connect-wallet :connect-wallet-action]
     [:actions/disconnect-wallet :disconnect-wallet-action]
     [:actions/open-ghost-mode-modal :open-ghost-mode-modal]
     [:actions/close-ghost-mode-modal :close-ghost-mode-modal]
     [:actions/set-ghost-mode-search :set-ghost-mode-search]
     [:actions/set-ghost-mode-label :set-ghost-mode-label]
     [:actions/start-ghost-mode :start-ghost-mode]
     [:actions/stop-ghost-mode :stop-ghost-mode]
     [:actions/add-ghost-mode-watchlist-address :add-ghost-mode-watchlist-address]
     [:actions/remove-ghost-mode-watchlist-address :remove-ghost-mode-watchlist-address]
     [:actions/edit-ghost-mode-watchlist-address :edit-ghost-mode-watchlist-address]
     [:actions/clear-ghost-mode-watchlist-edit :clear-ghost-mode-watchlist-edit]
     [:actions/copy-ghost-mode-watchlist-address :copy-ghost-mode-watchlist-address]
     [:actions/spectate-ghost-mode-watchlist-address :spectate-ghost-mode-watchlist-address]
     [:actions/enable-agent-trading :enable-agent-trading-action]
     [:actions/set-agent-storage-mode :set-agent-storage-mode-action]
     [:actions/copy-wallet-address :copy-wallet-address-action]
     [:actions/reconnect-websocket :reconnect-websocket-action]
     [:actions/toggle-ws-diagnostics :toggle-ws-diagnostics]
     [:actions/close-ws-diagnostics :close-ws-diagnostics]
     [:actions/toggle-ws-diagnostics-sensitive :toggle-ws-diagnostics-sensitive]
     [:actions/ws-diagnostics-reconnect-now :ws-diagnostics-reconnect-now]
     [:actions/ws-diagnostics-copy :ws-diagnostics-copy]
     [:actions/set-show-surface-freshness-cues :set-show-surface-freshness-cues]
     [:actions/toggle-show-surface-freshness-cues :toggle-show-surface-freshness-cues]
     [:actions/ws-diagnostics-reset-market-subscriptions :ws-diagnostics-reset-market-subscriptions]
     [:actions/ws-diagnostics-reset-orders-subscriptions :ws-diagnostics-reset-orders-subscriptions]
     [:actions/ws-diagnostics-reset-all-subscriptions :ws-diagnostics-reset-all-subscriptions]
     [:actions/toggle-asset-dropdown :toggle-asset-dropdown]
     [:actions/close-asset-dropdown :close-asset-dropdown]
     [:actions/select-asset :select-asset]
     [:actions/update-asset-search :update-asset-search]
     [:actions/update-asset-selector-sort :update-asset-selector-sort]
     [:actions/toggle-asset-selector-strict :toggle-asset-selector-strict]
     [:actions/toggle-asset-favorite :toggle-asset-favorite]
     [:actions/set-asset-selector-favorites-only :set-asset-selector-favorites-only]
     [:actions/set-asset-selector-tab :set-asset-selector-tab]
     [:actions/handle-asset-selector-shortcut :handle-asset-selector-shortcut]
     [:actions/set-asset-selector-scroll-top :set-asset-selector-scroll-top]
     [:actions/increase-asset-selector-render-limit :increase-asset-selector-render-limit]
     [:actions/show-all-asset-selector-markets :show-all-asset-selector-markets]
     [:actions/maybe-increase-asset-selector-render-limit :maybe-increase-asset-selector-render-limit]
     [:actions/refresh-asset-markets :refresh-asset-markets]
     [:actions/mark-loaded-asset-icon :mark-loaded-asset-icon]
     [:actions/mark-missing-asset-icon :mark-missing-asset-icon]
     [:actions/set-funding-hypothetical-size :set-funding-hypothetical-size]
     [:actions/set-funding-hypothetical-value :set-funding-hypothetical-value]
     [:actions/toggle-timeframes-dropdown :toggle-timeframes-dropdown]
     [:actions/select-chart-timeframe :select-chart-timeframe]
     [:actions/toggle-chart-type-dropdown :toggle-chart-type-dropdown]
     [:actions/select-chart-type :select-chart-type]
     [:actions/toggle-indicators-dropdown :toggle-indicators-dropdown]
     [:actions/update-indicators-search :update-indicators-search]
     [:actions/toggle-portfolio-summary-scope-dropdown :toggle-portfolio-summary-scope-dropdown]
     [:actions/select-portfolio-summary-scope :select-portfolio-summary-scope]
     [:actions/toggle-portfolio-summary-time-range-dropdown :toggle-portfolio-summary-time-range-dropdown]
     [:actions/toggle-portfolio-performance-metrics-time-range-dropdown :toggle-portfolio-performance-metrics-time-range-dropdown]
     [:actions/select-portfolio-summary-time-range :select-portfolio-summary-time-range]
     [:actions/select-portfolio-chart-tab :select-portfolio-chart-tab]
     [:actions/set-portfolio-account-info-tab :set-portfolio-account-info-tab]
     [:actions/set-portfolio-chart-hover :set-portfolio-chart-hover]
     [:actions/clear-portfolio-chart-hover :clear-portfolio-chart-hover]
     [:actions/set-portfolio-returns-benchmark-search :set-portfolio-returns-benchmark-search]
     [:actions/set-portfolio-returns-benchmark-suggestions-open :set-portfolio-returns-benchmark-suggestions-open]
     [:actions/select-portfolio-returns-benchmark :select-portfolio-returns-benchmark]
     [:actions/remove-portfolio-returns-benchmark :remove-portfolio-returns-benchmark]
     [:actions/handle-portfolio-returns-benchmark-search-keydown :handle-portfolio-returns-benchmark-search-keydown]
     [:actions/clear-portfolio-returns-benchmark :clear-portfolio-returns-benchmark]
     [:actions/toggle-orderbook-size-unit-dropdown :toggle-orderbook-size-unit-dropdown]
     [:actions/select-orderbook-size-unit :select-orderbook-size-unit]
     [:actions/toggle-orderbook-price-aggregation-dropdown :toggle-orderbook-price-aggregation-dropdown]
     [:actions/select-orderbook-price-aggregation :select-orderbook-price-aggregation]
     [:actions/select-orderbook-tab :select-orderbook-tab]
     [:actions/add-indicator :add-indicator]
     [:actions/remove-indicator :remove-indicator]
     [:actions/update-indicator-period :update-indicator-period]
     [:actions/show-volume-indicator :show-volume-indicator]
     [:actions/hide-volume-indicator :hide-volume-indicator]
     [:actions/select-account-info-tab :select-account-info-tab]
     [:actions/set-funding-history-filters :set-funding-history-filters]
     [:actions/toggle-funding-history-filter-open :toggle-funding-history-filter-open]
     [:actions/toggle-funding-history-filter-coin :toggle-funding-history-filter-coin]
     [:actions/add-funding-history-filter-coin :add-funding-history-filter-coin]
     [:actions/handle-funding-history-coin-search-keydown :handle-funding-history-coin-search-keydown]
     [:actions/reset-funding-history-filter-draft :reset-funding-history-filter-draft]
     [:actions/apply-funding-history-filters :apply-funding-history-filters]
     [:actions/view-all-funding-history :view-all-funding-history]
     [:actions/export-funding-history-csv :export-funding-history-csv]
     [:actions/set-funding-history-page-size :set-funding-history-page-size]
     [:actions/set-funding-history-page :set-funding-history-page]
     [:actions/next-funding-history-page :next-funding-history-page]
     [:actions/prev-funding-history-page :prev-funding-history-page]
     [:actions/set-funding-history-page-input :set-funding-history-page-input]
     [:actions/apply-funding-history-page-input :apply-funding-history-page-input]
     [:actions/handle-funding-history-page-input-keydown :handle-funding-history-page-input-keydown]
     [:actions/set-trade-history-page-size :set-trade-history-page-size]
     [:actions/set-trade-history-page :set-trade-history-page]
     [:actions/next-trade-history-page :next-trade-history-page]
     [:actions/prev-trade-history-page :prev-trade-history-page]
     [:actions/set-trade-history-page-input :set-trade-history-page-input]
     [:actions/apply-trade-history-page-input :apply-trade-history-page-input]
     [:actions/handle-trade-history-page-input-keydown :handle-trade-history-page-input-keydown]
     [:actions/sort-trade-history :sort-trade-history]
     [:actions/toggle-trade-history-direction-filter-open :toggle-trade-history-direction-filter-open]
     [:actions/set-trade-history-direction-filter :set-trade-history-direction-filter]
     [:actions/sort-positions :sort-positions]
     [:actions/toggle-positions-direction-filter-open :toggle-positions-direction-filter-open]
     [:actions/set-positions-direction-filter :set-positions-direction-filter]
     [:actions/sort-balances :sort-balances]
     [:actions/sort-open-orders :sort-open-orders]
     [:actions/toggle-open-orders-direction-filter-open :toggle-open-orders-direction-filter-open]
     [:actions/set-open-orders-direction-filter :set-open-orders-direction-filter]
     [:actions/sort-funding-history :sort-funding-history]
     [:actions/sort-order-history :sort-order-history]
     [:actions/toggle-order-history-filter-open :toggle-order-history-filter-open]
     [:actions/set-order-history-status-filter :set-order-history-status-filter]
     [:actions/set-account-info-coin-search :set-account-info-coin-search]
     [:actions/set-order-history-page-size :set-order-history-page-size]
     [:actions/set-order-history-page :set-order-history-page]
     [:actions/next-order-history-page :next-order-history-page]
     [:actions/prev-order-history-page :prev-order-history-page]
     [:actions/set-order-history-page-input :set-order-history-page-input]
     [:actions/apply-order-history-page-input :apply-order-history-page-input]
     [:actions/handle-order-history-page-input-keydown :handle-order-history-page-input-keydown]
     [:actions/refresh-order-history :refresh-order-history]
     [:actions/set-hide-small-balances :set-hide-small-balances]
     [:actions/open-position-tpsl-modal :open-position-tpsl-modal]
     [:actions/close-position-tpsl-modal :close-position-tpsl-modal]
     [:actions/handle-position-tpsl-modal-keydown :handle-position-tpsl-modal-keydown]
     [:actions/set-position-tpsl-modal-field :set-position-tpsl-modal-field]
     [:actions/set-position-tpsl-configure-amount :set-position-tpsl-configure-amount]
     [:actions/set-position-tpsl-limit-price :set-position-tpsl-limit-price]
     [:actions/submit-position-tpsl :submit-position-tpsl]
     [:actions/trigger-close-all-positions :trigger-close-all-positions]
     [:actions/open-position-reduce-popover :open-position-reduce-popover]
     [:actions/close-position-reduce-popover :close-position-reduce-popover]
     [:actions/handle-position-reduce-popover-keydown :handle-position-reduce-popover-keydown]
     [:actions/set-position-reduce-popover-field :set-position-reduce-popover-field]
     [:actions/set-position-reduce-size-percent :set-position-reduce-size-percent]
     [:actions/set-position-reduce-limit-price-to-mid :set-position-reduce-limit-price-to-mid]
     [:actions/submit-position-reduce-close :submit-position-reduce-close]
     [:actions/open-position-margin-modal :open-position-margin-modal]
     [:actions/close-position-margin-modal :close-position-margin-modal]
     [:actions/handle-position-margin-modal-keydown :handle-position-margin-modal-keydown]
     [:actions/set-position-margin-modal-field :set-position-margin-modal-field]
     [:actions/set-position-margin-amount-percent :set-position-margin-amount-percent]
     [:actions/set-position-margin-amount-to-max :set-position-margin-amount-to-max]
     [:actions/submit-position-margin-update :submit-position-margin-update]]
    (order-form-command-catalog/runtime-action-bindings)
    [[:actions/dismiss-order-feedback-toast :dismiss-order-feedback-toast]
     [:actions/cancel-order :cancel-order]
     [:actions/load-user-data :load-user-data]
     [:actions/set-funding-modal :set-funding-modal]
     [:actions/open-funding-transfer-modal :open-funding-transfer-modal]
     [:actions/open-funding-withdraw-modal :open-funding-withdraw-modal]
     [:actions/open-funding-deposit-modal :open-funding-deposit-modal]
     [:actions/close-funding-modal :close-funding-modal]
     [:actions/handle-funding-modal-keydown :handle-funding-modal-keydown]
     [:actions/set-funding-modal-field :set-funding-modal-field]
     [:actions/set-hyperunit-lifecycle :set-hyperunit-lifecycle]
     [:actions/clear-hyperunit-lifecycle :clear-hyperunit-lifecycle]
     [:actions/set-hyperunit-lifecycle-error :set-hyperunit-lifecycle-error]
     [:actions/set-funding-transfer-direction :set-funding-transfer-direction]
     [:actions/set-funding-amount-to-max :set-funding-amount-to-max]
     [:actions/submit-funding-transfer :submit-funding-transfer]
     [:actions/submit-funding-withdraw :submit-funding-withdraw]
     [:actions/submit-funding-deposit :submit-funding-deposit]
     [:actions/navigate :navigate]
     [:actions/load-funding-comparison-route :load-funding-comparison-route]
     [:actions/load-funding-comparison :load-funding-comparison]
     [:actions/set-funding-comparison-query :set-funding-comparison-query]
     [:actions/set-funding-comparison-timeframe :set-funding-comparison-timeframe]
     [:actions/set-funding-comparison-sort :set-funding-comparison-sort]
     [:actions/load-vault-route :load-vault-route]
     [:actions/load-vaults :load-vaults]
     [:actions/load-vault-detail :load-vault-detail]
     [:actions/set-vaults-search-query :set-vaults-search-query]
     [:actions/toggle-vaults-filter :toggle-vaults-filter]
     [:actions/set-vaults-snapshot-range :set-vaults-snapshot-range]
     [:actions/set-vaults-sort :set-vaults-sort]
     [:actions/set-vaults-user-page-size :set-vaults-user-page-size]
     [:actions/toggle-vaults-user-page-size-dropdown :toggle-vaults-user-page-size-dropdown]
     [:actions/close-vaults-user-page-size-dropdown :close-vaults-user-page-size-dropdown]
     [:actions/set-vaults-user-page :set-vaults-user-page]
     [:actions/next-vaults-user-page :next-vaults-user-page]
     [:actions/prev-vaults-user-page :prev-vaults-user-page]
     [:actions/set-vault-detail-tab :set-vault-detail-tab]
     [:actions/set-vault-detail-activity-tab :set-vault-detail-activity-tab]
     [:actions/sort-vault-detail-activity :sort-vault-detail-activity]
     [:actions/toggle-vault-detail-activity-filter-open :toggle-vault-detail-activity-filter-open]
     [:actions/close-vault-detail-activity-filter :close-vault-detail-activity-filter]
     [:actions/set-vault-detail-activity-direction-filter :set-vault-detail-activity-direction-filter]
     [:actions/set-vault-detail-chart-series :set-vault-detail-chart-series]
     [:actions/set-vault-detail-returns-benchmark-search :set-vault-detail-returns-benchmark-search]
     [:actions/set-vault-detail-returns-benchmark-suggestions-open :set-vault-detail-returns-benchmark-suggestions-open]
     [:actions/select-vault-detail-returns-benchmark :select-vault-detail-returns-benchmark]
     [:actions/remove-vault-detail-returns-benchmark :remove-vault-detail-returns-benchmark]
     [:actions/handle-vault-detail-returns-benchmark-search-keydown :handle-vault-detail-returns-benchmark-search-keydown]
     [:actions/clear-vault-detail-returns-benchmark :clear-vault-detail-returns-benchmark]
     [:actions/open-vault-transfer-modal :open-vault-transfer-modal]
     [:actions/close-vault-transfer-modal :close-vault-transfer-modal]
     [:actions/handle-vault-transfer-modal-keydown :handle-vault-transfer-modal-keydown]
     [:actions/set-vault-transfer-amount :set-vault-transfer-amount]
     [:actions/set-vault-transfer-withdraw-all :set-vault-transfer-withdraw-all]
     [:actions/submit-vault-transfer :submit-vault-transfer]
     [:actions/set-vault-detail-chart-hover :set-vault-detail-chart-hover]
     [:actions/clear-vault-detail-chart-hover :clear-vault-detail-chart-hover]])))

(defn- duplicate-ids
  [rows]
  (->> rows
       (map first)
       frequencies
       (keep (fn [[id freq]]
               (when (> freq 1)
                 id)))
       sort
       vec))

(defn- assert-unique-ids!
  [label rows]
  (when-let [duplicates (seq (duplicate-ids rows))]
    (throw (js/Error.
            (str label " contains duplicate ids: " (pr-str duplicates)))))
  rows)

(def ^:private validated-effect-binding-rows
  (assert-unique-ids! "effect registration catalog" effect-binding-rows-data))

(def ^:private validated-action-binding-rows
  (assert-unique-ids! "action registration catalog" action-binding-rows-data))

(defn effect-binding-rows
  []
  validated-effect-binding-rows)

(defn action-binding-rows
  []
  validated-action-binding-rows)

(defn effect-ids
  []
  (->> validated-effect-binding-rows
       (map first)
       set))

(defn action-ids
  []
  (->> validated-action-binding-rows
       (map first)
       set))

(defn effect-handler-keys
  []
  (->> validated-effect-binding-rows
       (map second)
       set))

(defn action-handler-keys
  []
  (->> validated-action-binding-rows
       (map second)
       set))
