(ns hyperopen.domain.trading
  (:require [hyperopen.domain.trading.core :as core]
            [hyperopen.domain.trading.market :as market]
            [hyperopen.domain.trading.validation :as validation]))

(def order-types core/order-types)
(def order-type-spec core/order-type-spec)
(def advanced-order-types core/advanced-order-types)
(def limit-like-order-types core/limit-like-order-types)
(def tif-options core/tif-options)
(def default-max-slippage-pct core/default-max-slippage-pct)
(def default-fees core/default-fees)
(def legacy-scale-skew->number core/legacy-scale-skew->number)
(def scale-min-order-count core/scale-min-order-count)
(def scale-max-order-count core/scale-max-order-count)
(def scale-min-endpoint-notional core/scale-min-endpoint-notional)

(def parse-num core/parse-num)
(def clamp-percent core/clamp-percent)
(def normalize-scale-skew-number core/normalize-scale-skew-number)
(def number->clean-string core/number->clean-string)
(def normalize-order-type core/normalize-order-type)
(def limit-like-type? core/limit-like-type?)
(def entry-mode-for-type core/entry-mode-for-type)
(def order-type-validator-id core/order-type-validator-id)
(def order-type-builder-id core/order-type-builder-id)
(def normalize-entry-mode core/normalize-entry-mode)
(def normalize-pro-order-type core/normalize-pro-order-type)
(def market-max-leverage core/market-max-leverage)
(def normalize-ui-leverage core/normalize-ui-leverage)

(def available-to-trade market/available-to-trade)
(def position-for-active-asset market/position-for-active-asset)
(def current-position-summary market/current-position-summary)
(def base-size-string market/base-size-string)
(def best-bid-price market/best-bid-price)
(def best-ask-price market/best-ask-price)
(def reference-price market/reference-price)
(def mid-price-summary market/mid-price-summary)
(def effective-limit-price market/effective-limit-price)
(def effective-limit-price-string market/effective-limit-price-string)
(def mid-price-string market/mid-price-string)
(def size-from-percent market/size-from-percent)
(def percent-from-size market/percent-from-size)
(def apply-size-percent market/apply-size-percent)
(def sync-size-from-percent market/sync-size-from-percent)
(def sync-size-percent-from-size market/sync-size-percent-from-size)
(def order-summary market/order-summary)
(def best-price market/best-price)
(def apply-market-price market/apply-market-price)

(def validation-error-message validation/validation-error-message)
(def validation-errors->messages validation/validation-errors->messages)
(def validate-order-form validation/validate-order-form)
(def submit-required-fields validation/submit-required-fields)

(def order-side->is-buy core/order-side->is-buy)
(def opposite-side core/opposite-side)
(def scale-weights core/scale-weights)
(def scale-order-legs core/scale-order-legs)
(def scale-preview-boundaries core/scale-preview-boundaries)
