export const SECURITY_HEADERS_FILE_PATH = "_headers";
export const CONTROL_CACHE_CONTROL = "public, max-age=0, must-revalidate";
export const IMMUTABLE_CACHE_CONTROL = "public, max-age=31556952, immutable";
export const DOCUMENT_PERMISSIONS_POLICY = [
  "accelerometer=()",
  "autoplay=()",
  "camera=()",
  "display-capture=()",
  "geolocation=()",
  "gyroscope=()",
  "microphone=()",
  "payment=()",
  "usb=()",
  "xr-spatial-tracking=()",
].join(", ");
export const DOCUMENT_REFERRER_POLICY = "strict-origin-when-cross-origin";

const DOCUMENT_CONNECT_SRC = [
  "'self'",
  "https://cloudflareinsights.com",
  "https://api.hyperliquid.xyz",
  "wss://api.hyperliquid.xyz",
  "https://stats-data.hyperliquid.xyz",
  "https://app.hyperliquid.xyz",
  "https://api.hyperunit.xyz",
  "https://api.hyperunit-testnet.xyz",
  "https://app.across.to",
  "https://li.quest",
];

const DOCUMENT_IMG_SRC = [
  "'self'",
  "data:",
  "blob:",
  "https://app.hyperliquid.xyz",
];

function appendDirective(directives, name, values) {
  if (!Array.isArray(values) || values.length === 0) {
    directives.push(name);
    return;
  }

  directives.push(`${name} ${values.join(" ")}`);
}

function normalizeImmutableAssetPath(assetPath) {
  const normalized = String(assetPath || "").trim();
  if (!normalized.startsWith("/")) {
    throw new Error(`Expected immutable asset paths to start with '/': ${assetPath}`);
  }

  return normalized;
}

function formatHeaderBlock(pattern, entries) {
  const lines = [pattern];

  for (const entry of entries) {
    if (entry?.detach) {
      lines.push(`  ! ${entry.name}`);
      continue;
    }

    lines.push(`  ${entry.name}: ${entry.value}`);
  }

  return lines.join("\n");
}

export function buildContentSecurityPolicy() {
  const directives = [];

  appendDirective(directives, "default-src", ["'self'"]);
  appendDirective(directives, "base-uri", ["'self'"]);
  appendDirective(directives, "form-action", ["'self'"]);
  appendDirective(directives, "object-src", ["'none'"]);
  appendDirective(directives, "script-src", ["'self'", "https://static.cloudflareinsights.com"]);
  appendDirective(directives, "style-src", ["'self'", "'unsafe-inline'"]);
  appendDirective(directives, "style-src-elem", ["'self'", "'unsafe-inline'"]);
  appendDirective(directives, "style-src-attr", ["'unsafe-inline'"]);
  appendDirective(directives, "font-src", ["'self'", "data:"]);
  appendDirective(directives, "img-src", DOCUMENT_IMG_SRC);
  appendDirective(directives, "connect-src", DOCUMENT_CONNECT_SRC);
  appendDirective(directives, "worker-src", ["'self'"]);
  appendDirective(directives, "child-src", ["'self'"]);
  appendDirective(directives, "frame-src", ["'none'"]);
  appendDirective(directives, "frame-ancestors", ["'none'"]);
  appendDirective(directives, "manifest-src", ["'self'"]);
  appendDirective(directives, "media-src", ["'self'", "blob:"]);

  return `${directives.join("; ")};`;
}

export function expectedDocumentHeaders() {
  return {
    "content-security-policy": buildContentSecurityPolicy(),
    "x-frame-options": "DENY",
    "x-content-type-options": "nosniff",
    "referrer-policy": DOCUMENT_REFERRER_POLICY,
    "permissions-policy": DOCUMENT_PERMISSIONS_POLICY,
    "cache-control": CONTROL_CACHE_CONTROL,
  };
}

export function buildReleaseHeadersFile({
  immutableAssetPaths = [],
} = {}) {
  const normalizedImmutableAssetPaths = [...new Set(immutableAssetPaths.map(normalizeImmutableAssetPath))]
    .sort();
  const documentHeaders = expectedDocumentHeaders();
  const lines = [
    "# Generated by tools/release-assets/security_headers.mjs",
    "# Cloudflare Pages applies these rules to the published static release root.",
    "",
    formatHeaderBlock("/*", [
      {
        name: "Content-Security-Policy",
        value: documentHeaders["content-security-policy"],
      },
      { name: "X-Frame-Options", value: documentHeaders["x-frame-options"] },
      {
        name: "X-Content-Type-Options",
        value: documentHeaders["x-content-type-options"],
      },
      { name: "Referrer-Policy", value: documentHeaders["referrer-policy"] },
      {
        name: "Permissions-Policy",
        value: documentHeaders["permissions-policy"],
      },
      { name: "Cache-Control", value: documentHeaders["cache-control"] },
    ]),
  ];

  for (const assetPath of normalizedImmutableAssetPaths) {
    lines.push(
      "",
      formatHeaderBlock(assetPath, [
        { detach: true, name: "Cache-Control" },
        { name: "Cache-Control", value: IMMUTABLE_CACHE_CONTROL },
      ]),
    );
  }

  return `${lines.join("\n")}\n`;
}
